# Generated by Django 5.0.6 on 2024-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('security', 'Security'), ('pentest', 'Pentest')], max_length=50),
        ),
    ]
